name: journal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/escaping.svg
    - assets/illustrations/pineapple.svg
    - .env
